from app.algorithms.conflict_detector import detect_conflicts, build_exam_conflict_graph, welsh_powell_coloring
from app.algorithms.study_allocator import knapsack_allocate, compute_priority_score, generate_daily_allocations
from app.algorithms.adaptive_replanner import greedy_reschedule
from app.algorithms.plan_generator import PlanGenerator
